blank_issues_enabled: true
contact_links:
  - name: Don't have a GitHub account? Unsure how to use GitHub?
    url: https://docs.qq.com/form/page/DSlFOZmpTQ1JsZ2FD
    about: Click here to submit a bug report via Tencent Docs